version: '3'

services:

  app:
    image: php:${PHP_VERSION}-fpm
    container_name: ${APP_NAME}_app
    restart: unless-stopped
    volumes:
      - ./public:/var/www/html
    networks:
      - network_backend
    depends_on:
      - db

  web:
    image: nginx:${NGINX_VERSION}
    container_name: ${APP_NAME}_web
    restart: unless-stopped
    volumes:
      - ./config/web/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./storage/web/logs:/var/log/nginx
    volumes_from:
      - app
    ports:
      - ${WEB_HTTP_PORT}:80
      - ${WEB_HTTPS_PORT}:443
    depends_on:
      - app
    networks:
      - network_backend
      - network_frontend
    depends_on:
      - app

  db:
    image: postgres:${POSTGRES_VERSION}
    container_name: ${APP_NAME}_db
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${APP_NAME}
    volumes:
      - ./storage/db:/var/lib/postgresql/data
    networks:
      - network_backend

  db_admin:
    image: dpage/pgadmin4
    container_name: ${APP_NAME}_db_admin
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=${DB_ADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${DB_ADMIN_DEFAULT_PASSWORD}
    volumes:
      - ./storage/db_admin:/var/lib/pgadmin
      # set 'sudo chown -R 5050:5050 ./storage/db_admin' cause pgAdmin runs as the pgadmin user (UID: 5050) in the pgadmin group (GID: 5050) in the container
    ports:
      - ${DB_ADMIN_HTTP_PORT}:80
      - ${DB_ADMIN_HTTP_PORT}:443
    networks:
      - network_backend
      - network_frontend
    depends_on:
      - db

networks:
    network_backend:
        name: ${APP_NAME}_network
        driver: bridge
        driver_opts:
            com.docker.network.enable_ipv6: "false"
    network_frontend:
        name: ${APP_NAME}_network_public
        driver: bridge
        driver_opts:
            com.docker.network.enable_ipv6: "false"
